#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking your commit message"

commit_regex="^\[(Feature|BugFix|HotFix)\] .*$"
error_msg="Bad commit message. See examle: \"[Feature] Implement UI Login\""

commit_message="$(cat $1)"
if [[ ! $commit_message =~ $commit_regex ]]
then
    echo $error_msg >&2
    exit 1
fi
